name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make
