name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Make and g++
        run: sudo apt-get update && sudo apt-get install -y make && sudo apt-get install g++ -y
      - name: Build project
        run: |
          mkdir build
          make
